import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import ExcelJS from 'exceljs';
import { createApp } from '../src/app.js';
import { AuthService } from '../src/auth/service.js';
import { InMemoryAuthRepository } from '../src/auth/repository.js';
import { InMemorySubmissionRepository } from '../src/submission/repository.js';
import { SubmissionService } from '../src/submission/service.js';
import { tableHeaders, type TablePage } from '../src/submission/table.js';

const users = new InMemoryAuthRepository();
const records = new InMemorySubmissionRepository();
let verification = '';
const auth = new AuthService(users, { async sendEmailVerification(_email, token) { verification = token; }, async sendPasswordReset() {} });
const service = new SubmissionService(records, ['www.bilibili.com'], event => users.insertAuditEvent(event));
const app = createApp({ auth, submissions: service });
const credentials = { email: 'summary-test@example.com', password: 'Summary-test-long-password-123' };
const json = { 'content-type': 'application/json' };
await app.request('/api/v1/auth/register', { method: 'POST', headers: json, body: JSON.stringify(credentials) });
await app.request(`/api/v1/auth/verify-email?token=${verification}`);
const login = await app.request('/api/v1/auth/login', { method: 'POST', headers: json, body: JSON.stringify(credentials) });
assert.equal(login.status, 200);
const cookie = login.headers.getSetCookie().map(c => c.split(';')[0]).join('; ');
const csrf = cookie.match(/chinavr-csrf=([^;]+)/)![1]!;
const participant = [...users.users.values()][0]!;
const admin = { ...participant, roles: ['event_admin'] as typeof participant.roles, mfaEnabled: true };
const url = '/api/v1/admin/submissions/table';
const exportUrl = url + '/export';
const get = (suffix = '') => app.request(url + suffix, { headers: { cookie } });
const exportRows = (filter: object = {}, token = csrf) => app.request(exportUrl, { method: 'POST', headers: { ...json, cookie, 'x-csrf-token': token }, body: JSON.stringify(filter) });
assert.equal((await app.request(url)).status, 401);
assert.equal((await get()).status, 403);
assert.equal((await exportRows()).status, 403);
users.users.set(admin.id, { ...admin, mfaEnabled: false });
assert.equal((await get()).status, 403);
assert.equal((await exportRows()).status, 403);
users.users.set(admin.id, admin);
assert.equal((await exportRows({}, '')).status, 403);
assert.equal((await get('?page=0')).status, 422);
assert.equal((await exportRows({ unknown: true })).status, 422);
assert.equal((await get()).headers.get('cache-control'), 'no-store');
assert.equal(((await (await get()).json()) as TablePage).total, 0);

const draft = await service.createDraft(participant, { title: '尚未提交的草稿', direction: 'frontier_tech', workForm: 'animation' }, 'table-test-draft');
const longText = '完整的创作说明\n'.repeat(200);
for (let i = 0; i < 53; i++) {
  const time = new Date(Date.UTC(2026, 8, 1, 0, i));
  await records.insert({ ...draft, id: randomUUID(), receiptNo: `CVR26-HIST-${i}`, submittedAt: time, currentStatus: i === 52 ? 'withdrawn' : 'submitted', createdAt: time, updatedAt: time,
    draft: { ...draft.draft, title: i === 52 ? '=1+1' : `历史作品 ${i}`, synopsis: '中文、逗号,"引号"\n换行', creativeStatement: longText, rightsConfirmed: true, aiLabelConfirmed: true, templateConfirmed: null },
    mediaLinks: [{ id: randomUUID(), purpose: 'mainWork', originalUrl: 'https://www.bilibili.com/video/BVTEST', canonicalUrl: null, provider: 'bilibili', externalVideoId: null, isPubliclyAccessible: null, durationSeconds: null, width: null, height: null, precheckStatus: 'pending', failureCode: null, precheckFindings: [], checkedAt: null, expiresAt: null }],
  });
}
const first = (await (await get()).json()) as TablePage;
const second = (await (await get('?page=2')).json()) as TablePage;
assert.equal(first.total, 53);
assert.equal(first.items.length, 50);
assert.equal(second.items.length, 3);
assert.equal(new Set([...first.items, ...second.items].map(r => r.id)).size, 53);
assert.equal(first.items[0]!.cells[1], '2026-09-01 08:52:00');
assert.equal(first.items[0]!.cells[2], credentials.email);
assert.equal(first.items[0]!.cells[3], '=1+1');
assert.equal(first.items[0]!.cells[18], '');
assert.ok(!JSON.stringify(first).includes('https://www.bilibili.com'));
assert.ok(!JSON.stringify(first).includes('passwordHash'));
const filtered = (await (await get('?status=withdrawn&q=summary-test')).json()) as TablePage;
assert.equal(filtered.total, 1);
assert.equal(filtered.items[0]!.cells[6], '已撤回');
const response = await exportRows();
assert.equal(response.status, 200);
assert.match(response.headers.get('content-type')!, /spreadsheetml/);
const workbook = new ExcelJS.Workbook();
await workbook.xlsx.load(await response.arrayBuffer());
const sheet = workbook.getWorksheet('投稿汇总')!;
assert.equal(sheet.rowCount, 54);
assert.equal(sheet.columnCount, tableHeaders.length);
assert.equal(sheet.getCell('D2').value, '=1+1');
assert.equal(sheet.getCell('D2').type, ExcelJS.ValueType.String);
assert.equal(sheet.getCell('K2').value, longText);
assert.equal(sheet.getCell('J2').value, '中文、逗号,"引号"\n换行');
assert.equal(sheet.getCell('S2').value, 'https://www.bilibili.com/video/BVTEST');
assert.equal(sheet.getCell('T2').value, '待核验');
assert.equal(sheet.getCell('R2').value, '未填写');
assert.equal(users.auditEvents.filter(e => e.action === 'admin.submission.export').length, 53);
const filteredBook = new ExcelJS.Workbook();
await filteredBook.xlsx.load(await (await exportRows({ status: 'withdrawn' })).arrayBuffer());
assert.equal(filteredBook.getWorksheet('投稿汇总')!.rowCount, 2);
assert.equal(users.auditEvents.filter(e => e.action === 'admin.submission.export').length, 54);
const emptyBook = new ExcelJS.Workbook();
await emptyBook.xlsx.load(await (await exportRows({ q: '完全不匹配' })).arrayBuffer());
assert.equal(emptyBook.getWorksheet('投稿汇总')!.rowCount, 1);
const latest = { ...draft, id: randomUUID(), receiptNo: 'CVR26-NEW', submittedAt: new Date(), currentStatus: 'submitted' as const };
await records.insert(latest);
const updated = (await (await get()).json()) as TablePage;
assert.equal(updated.total, 54);
assert.equal(updated.items[0]!.id, latest.id);
users.users.set(participant.id, participant);
assert.equal((await get()).status, 403);
assert.equal((await exportRows()).status, 403);
console.log('PASS 汇总表：历史与新增投稿、跨页无遗漏、筛选、权限/MFA/CSRF、完整 XLSX、公式文本与审计');
